[package]
name = "bounce_shield"
version = "1.0.0"
edition = "2024"

[lib]
name = "bounce_shield"
path = "lib/lib.rs"

[dependencies]
rand = "0.8.5"
ggez = { version = "0.9.3", default-features = false, features = ["audio"] }
